const SITE_CONTAINER = "site-container";
const INTRO_TEXT_CONTAINER_ID = "introText-container";
const INTRO_TEXT_ID = "intro-text-";
const INTRO_TEXT2_ID = "intro2-text-";
const INTRO1_TEXT = ["HELLO", "MY","NAME","IS","RICH"];
const INTRO2_TEXT = ["I", "AM A","WEB DEVELOPER","AND","DESIGNER"];

displayIntro(SITE_CONTAINER, INTRO1_TEXT, INTRO_TEXT_CONTAINER_ID, INTRO_TEXT_ID);
replaceIntro(INTRO_TEXT_CONTAINER_ID, 5000, SITE_CONTAINER, INTRO2_TEXT, INTRO_TEXT_CONTAINER_ID, INTRO_TEXT2_ID);